services:
  sales-dashboard:
    build:
      context: .
      dockerfile: Dockerfile.nextjs
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    env_file:
      - .env.local
    depends_on:
      - playwright-mcp
    networks:
      - app-network

  playwright-mcp:
    build:
      context: .
      dockerfile: Dockerfile.playwright-mcp
    ports:
      - "3001:3001"
    environment:
      - MCP_SERVER_PORT=3001
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
    volumes:
      - playwright-data:/ms-playwright
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  playwright-data: